config/routes.rb
Brewtronic5000::Application.routes.draw do
  get "reporting/ttb"
  post "reporting/ttb"

  get "reporting/grain"
  post "reporting/grain"

  get "reporting/hop"
  post "reporting/hop"

  get "reporting/fermenter"
  post "reporting/fermenter"

  resources :hop_contracts

  resources :hop_transactions

  resources :grain_transactions

  resources :yeast_manufacturers

  resources :styles

  resources :recipe_minerals

  resources :recipes

  resources :mash_types

  resources :minerals

  resources :yeasts

  resources :batches

  resources :fermenters

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :hop_inventories

  get "home/index"

  resources :grain_inventories

  resources :grain_suppliers

  resources :grains

  resources :hop_suppliers

  resources :hops

  match 'recipes/:id/duplicate' => 'recipes#duplicate', :as => :duplicate_recipe
  match 'batches/:id/duplicate' => 'batches#duplicate', :as => :duplicate_batch

  authenticated :user do
      root :to => 'home#index'   
  end

  root :to => 'home#index'

end

app/models/hop_inventory.rb
class HopInventory < ActiveRecord::Base
  include Searchable

  def is_valid_year?(date_str, start_year=1900, end_year=2099)
    date_str.grep(/^(\d)+$/) { |date_str|
      (start_year..end_year).include?(date_str.to_i)
    }.first
  end

  attr_accessor :unit #Virtual field for units in forms
  attr_accessible :unit #Virtual field for units in forms

  belongs_to :hop
  belongs_to :hop_supplier
  has_many :hop_transactions
  attr_accessible :amount, :crop_year, :hop_type, :hop_id, :hop_supplier_id
  attr_accessible :storage_temp, :storage_factor, :harvest_date
  validates :hop_id, :uniqueness => {:scope => [:crop_year, :hop_supplier_id]}
  validates :hop_type, :presence => true

  self.per_page = 10

  def self.search_query(search)
    joins(:hop).where('hops.name LIKE ?', "%#{search}%")
  end

  def current_alpha
    factors = self.hop.hsi * self.storage_temp * self.storage_factor
    date = Date.today - self.harvest_date
    self.hop.alpha * ( 1 / Math.log(factors * date))
  end

end

app/controllers/hop_inventories_controller.rb
class HopInventoriesController < ApplicationController
  include SortableController
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  # GET /hop_inventories
  # GET /hop_inventories.json
  def index
    @hop_inventories = HopInventory.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page])
  end

  # GET /hop_inventories/1
  # GET /hop_inventories/1.json
  def show
    @hop_inventory = HopInventory.find(params[:id])
  end

  # GET /hop_inventories/new
  # GET /hop_inventories/new.json
  def new
    @hop_inventory = HopInventory.new
  end

  # GET /hop_inventories/1/edit
  def edit
    @hop_inventory = HopInventory.find(params[:id])
    @hop_inventory.amount = Units.format_mass_for_user(@hop_inventory.amount, current_user).value
  end

  # POST /hop_inventories
  # POST /hop_inventories.json
  def create
     params[:hop_inventory][:amount] = Units.convert_mass_units(params[:hop_inventory][:amount],params[:hop_inventory][:unit])

    @hop_inventory = HopInventory.new(params[:hop_inventory])

    respond_to do |format|
      if @hop_inventory.save
        format.html { redirect_to action: "index" and flash[:notice] = "#{@hop_inventory.hop.name}(#{@hop_inventory.crop_year}) was successfully created." }
        format.json { render json: @hop_inventory, status: :created, location: @hop_inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @hop_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hop_inventories/1
  # PUT /hop_inventories/1.json
  def update
    params[:hop_inventory][:amount] = Units.convert_mass_units(params[:hop_inventory][:amount],params[:hop_inventory][:unit])
    @hop_inventory = HopInventory.find(params[:id])

    respond_to do |format|
      if @hop_inventory.update_attributes(params[:hop_inventory])
        format.html { redirect_to @hop_inventory, notice: 'Hop inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hop_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hop_inventories/1
  # DELETE /hop_inventories/1.json
  def destroy
    @hop_inventory = HopInventory.find(params[:id])
    @hop_inventory.destroy

    respond_to do |format|
      format.html { redirect_to hop_inventories_url }
      format.json { head :no_content }
    end
  end

  def model
    HopInventory
  end

  def default_sort_column
    "hop_id"
  end

end

app/helpers/hop_inventories_helper.rb
module HopInventoriesHelper
end

app/views/hop_inventories/_form.html.erb
<%= form_for(@hop_inventory) do |f| %>
  <% if @hop_inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hop_inventory.errors.count, "error") %> prohibited this hop_inventory from being saved:</h2>

      <ul>
      <% @hop_inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hop_id %><br />
    <%= f.select :hop_id, Hop.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :hop_supplier_id %><br />
    <%= f.select :hop_supplier_id, HopSupplier.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :crop_year %><br />
    <%= f.text_field :crop_year %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
    <%= f.select :unit, options_for_select(["kg", "lb", "oz", "g"], :selected => current_user.mass_units)%>
  </div>
  <div class="field">
    <%= f.label :hop_type %><br />
    <%= f.select :hop_type, options_for_select(["Whole", "Pellet", "Plug"])%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hop_inventories/_form.html.haml
.group
  = f.label :hop_id, t("activerecord.attributes.hop_inventory.hop_id", :default => "Hop"), :class => :label
  = f.select :hop, Hop.all.collect {|c| [c.name, c.id]}  
  %span.description Ex: a simple text
.group
  = f.label :hop_supplier_id, t("activerecord.attributes.hop_inventory.hop_supplier_id", :default => "Hop supplier"), :class => :label
  = f.select :hop_supplier_id, HopSupplier.all.collect {|c| [c.name, c.id]}
  %span.description Ex: a simple text
.group
  = f.label :crop_year, t("activerecord.attributes.hop_inventory.crop_year", :default => "Crop year"), :class => :label
  = f.number_field :crop_year, :class => 'number_field'
  %span.description Ex: a simple text
.group
  = f.label :amount, t("activerecord.attributes.hop_inventory.amount", :default => "Amount"), :class => :label
  = f.text_field :amount, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :type, t("activerecord.attributes.hop_inventory.type", :default => "Type"), :class => :label
  = f.text_field :type, :class => 'text_field'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), hop_inventories_path, :class => "text_button_padding link_button"

app/views/hop_inventories/_hop_inventories.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sortable "hop_id", "Hop" %></th>
      <th><%= sortable "hop_supplier_id", "Hop Supplier" %></th>
      <th><%= sortable "crop_year" %></th>
      <th><%= sortable "amount" %></th>
      <th><%= sortable "hop_type", "Type" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @hop_inventories.each do |hop_inventory| %>
    <tr>
      <td><%= link_to hop_inventory.hop.name, hop_inventory unless hop_inventory.hop.nil? %></td>
      <td><%= hop_inventory.hop_supplier.name unless hop_inventory.hop_supplier.nil? %></td>
      <td><%= hop_inventory.crop_year %></td>
      <td><%= Units.format_mass_for_user(hop_inventory.amount, current_user)%></td>
      <td><%= hop_inventory.hop_type %></td>
      <td>
        <div class="pull-right">
          <%= link_to 'Destroy', hop_inventory, method: :delete, data: { confirm: 'Are you sure?', type: 'json'}, remote: 'true', :rel => 'nofollow', :class => 'btn btn-mini btn-danger delete_row' %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @hop_inventories %>

app/views/hop_inventories/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/hop_inventories/edit.html.erb
<h1>Editing Hop Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @hop_inventory %> |
<%= link_to 'Back', hop_inventories_path %>

app/views/hop_inventories/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_inventory_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_hop_inventory_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      HopInventory
    .inner
      = form_for @hop_inventory, :url => hop_inventory_path(@hop_inventory), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_inventories/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'index_table' %>
<% end %>
<h1>Hop Inventory</h1>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <%= form_tag hop_inventories_path, :method => 'get', :id => "table_search", :class => "navbar-search pull-left", :autocomplete => "off" do %>
          <%= text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search" %>
        <% end %>
        <%= link_to raw('<i class="icon-plus-sign icon-white"></i> New Hop Transaction'), new_hop_transaction_path, :class => 'btn btn-primary pull-right'%>
      </div>
    </div>
  </div>
  <div id="index_table"><%= render 'hop_inventories' %></div>
</div>

app/views/hop_inventories/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", hop_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_inventory_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      HopInventories
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.hop_inventory.hop_id", :default => t("activerecord.labels.hop_id", :default => "Hop_id"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @hop_inventories.each do |hop_inventory|
          %tr{:class => cycle("odd", "even")}
            %td
              = hop_inventory.id
            %td
              = link_to hop_inventory.hop_id, hop_inventory_path(hop_inventory)
            %td
              = hop_inventory.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", hop_inventory_path(hop_inventory)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_hop_inventory_path(hop_inventory)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", hop_inventory_path(hop_inventory), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @hop_inventories
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_inventories/index.js.erb
$("#index_table").html("<%= escape_javascript(render("hop_inventories")) %>");

app/views/hop_inventories/new.html.erb
<h1>New Hop Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', hop_inventories_path %>

app/views/hop_inventories/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_inventories_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_inventory_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      HopInventory
    .inner
      = form_for :hop_inventory, :url => hop_inventories_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Hop:</b>
  <%= @hop_inventory.hop.name unless @hop_inventory.hop.nil? %>
</p>

<p>
  <b>Hop supplier:</b>
  <%= @hop_inventory.hop_supplier.name unless @hop_inventory.hop_supplier.nil? %>
</p>

<p>
  <b>Crop year:</b>
  <%= @hop_inventory.crop_year %>
</p>

<p>
  <b>Amount:</b>
  <%= Units.format_mass_for_user(@hop_inventory.amount, current_user) %>
</p>

<p>
  <b>Type:</b>
  <%= @hop_inventory.hop_type %>
</p>

<p>
  <b>Storage Temp:</b>
  <%= @hop_inventory.storage_temp %>
</p>

<p>
  <b>Storage factor:</b>
  <%= @hop_inventory.storage_factor %>
</p>

<p>
  <b>Harvest Date:</b>
  <%= @hop_inventory.harvest_date %>
</p>

<p>
  <b>Hop Transactions:</b>
  <ul>
    <% @hop_inventory.hop_transactions.each do |t| %>
      <li> <%= link_to "%s, Added on %s" % [Units.format_mass_for_user(t.amount * t.quantity, current_user), t.created_at.localtime.strftime('%F %r')], t %> </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_hop_inventory_path(@hop_inventory) %> |
<%= link_to 'Back', hop_inventories_path %>

app/views/hop_inventories/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_inventory_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", hop_inventory_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.hop_inventory.hop_id", :default => t("activerecord.labels.hop_id", :default => "Hop"))
          \:
        = @hop_inventory.hop_id
      %p
        %b
          = t("activerecord.attributes.hop_inventory.hop_supplier_id", :default => t("activerecord.labels.hop_supplier_id", :default => "Hop supplier"))
          \:
        = @hop_inventory.hop_supplier_id
      %p
        %b
          = t("activerecord.attributes.hop_inventory.crop_year", :default => t("activerecord.labels.crop_year", :default => "Crop year"))
          \:
        = @hop_inventory.crop_year
      %p
        %b
          = t("activerecord.attributes.hop_inventory.amount", :default => t("activerecord.labels.amount", :default => "Amount"))
          \:
        = @hop_inventory.amount
      %p
        %b
          = t("activerecord.attributes.hop_inventory.type", :default => t("activerecord.labels.type", :default => "Type"))
          \:
        = @hop_inventory.type
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_hop_inventory_path(@hop_inventory), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), hop_inventory_path(@hop_inventory), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')