config/routes.rb
Brewtronic5000::Application.routes.draw do
  get "reporting/ttb"
  post "reporting/ttb"

  get "reporting/grain"
  post "reporting/grain"

  get "reporting/hop"
  post "reporting/hop"

  get "reporting/fermenter"
  post "reporting/fermenter"

  resources :hop_contracts

  resources :hop_transactions

  resources :grain_transactions

  resources :yeast_manufacturers

  resources :styles

  resources :recipe_minerals

  resources :recipes

  resources :mash_types

  resources :minerals

  resources :yeasts

  resources :batches

  resources :fermenters

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :hop_inventories

  get "home/index"

  resources :grain_inventories

  resources :grain_suppliers

  resources :grains

  resources :hop_suppliers

  resources :hops

  match 'recipes/:id/duplicate' => 'recipes#duplicate', :as => :duplicate_recipe
  match 'batches/:id/duplicate' => 'batches#duplicate', :as => :duplicate_batch

  authenticated :user do
      root :to => 'home#index'   
  end

  root :to => 'home#index'

end

app/models/grain_inventory.rb
class GrainInventory < ActiveRecord::Base
  include Searchable
  attr_accessible :amount, :grain_id, :grain_supplier_id
  attr_accessor :unit # Virtual field for units in forms
  attr_accessible :unit # Virtual field for units in forms
  belongs_to :grain
  belongs_to :grain_supplier
  has_many :grain_transactions
  validates :amount, :numericality => true
  validates :grain_id, :uniqueness => {:scope => :grain_supplier_id}

  self.per_page = 10

  def self.search_query(search)
    joins(:grain).where('grains.name LIKE ?', "%#{search}%")
  end
 
end

app/controllers/grain_inventories_controller.rb
class GrainInventoriesController < ApplicationController
  include SortableController
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  # GET /grain_inventories
  # GET /grain_inventories.json
  def index
    @grain_inventories= GrainInventory.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page])
  end

  # GET /grain_inventories/1
  # GET /grain_inventories/1.json
  def show
    @grain_inventory = GrainInventory.find(params[:id])
  end

  # GET /grain_inventories/new
  # GET /grain_inventories/new.json
  def new
    @grain_inventory = GrainInventory.new
  end

  # GET /grain_inventories/1/edit
  def edit
    @grain_inventory = GrainInventory.find(params[:id])
    @grain_inventory.amount = Units.format_mass_for_user(@grain_inventory.amount, current_user).value
  end

  # POST /grain_inventories
  # POST /grain_inventories.json
  def create
    params[:grain_inventory][:amount] = Units.convert_mass_units(params[:grain_inventory][:amount],params[:grain_inventory][:unit])

    @grain_inventory = GrainInventory.new(params[:grain_inventory])
    respond_to do |format|
      if @grain_inventory.save
        format.html { redirect_to @grain_inventory, notice: 'Grain inventory was successfully created.' }
        format.json { render json: @grain_inventory, status: :created, location: @grain_inventory }
      else
        format.html { render action: "new" }
        format.json { render json: @grain_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /grain_inventories/1
  # PUT /grain_inventories/1.json
  def update
    params[:grain_inventory][:amount] = Units.convert_mass_units(params[:grain_inventory][:amount],params[:grain_inventory][:unit])
   
    @grain_inventory = GrainInventory.find(params[:id])
    respond_to do |format|
      if @grain_inventory.update_attributes(params[:grain_inventory])
        format.html { redirect_to @grain_inventory, notice: 'Grain inventory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @grain_inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grain_inventories/1
  # DELETE /grain_inventories/1.json
  def destroy
    @grain_inventory = GrainInventory.find(params[:id])
    @grain_inventory.destroy

    respond_to do |format|
      format.html { redirect_to grain_inventories_url }
      format.json { head :no_content }
    end
  end

  def model
    GrainInventory
  end

  def default_sort_column
    "grain_id"
  end
    
end

app/helpers/grain_inventories_helper.rb
module GrainInventoriesHelper
end

app/views/grain_inventories/_form.html.erb
<%= form_for(@grain_inventory) do |f| %>
  <% if @grain_inventory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grain_inventory.errors.count, "error") %> prohibited this grain_inventory from being saved:</h2>

      <ul>
      <% @grain_inventory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
    <%= f.select :unit, options_for_select(["kg", "lb"], :selected => current_user.mass_units)%>
  </div>
  <div class="field">
    <%= f.label :grain_id %><br />
    <%= f.select :grain_id, Grain.all.collect {|c| [c.name, c.id]} %>
  </div>
  <div class="field">
    <%= f.label :grain_supplier_id %><br />
    <%= f.select :grain_supplier_id, GrainSupplier.all.collect {|c| [c.name, c.id]}, :selected => current_user.mass_units %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grain_inventories/_form.html.haml
.group
  = f.label :amount, t("activerecord.attributes.grain_inventory.amount", :default => "Amount"), :class => :label
  = f.text_field :amount, :class => 'text_field'
  %span.description Ex: a simple text
.group
  = f.label :grain_id, t("activerecord.attributes.grain_inventory.grain_id", :default => "Grain"), :class => :label
  = f.select :grain_id, Grain.all.collect {|c| [c.name, c.id]}
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), grain_inventories_path, :class => "text_button_padding link_button"

app/views/grain_inventories/_grain_inventories.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sortable "grain_id", "Grain name" %></th>
      <th><%= sortable "grain_supplier_id", "Grain Supplier" %></th>
      <th><%= sortable "amount" %></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @grain_inventories.each do |grain_inventory| %>
    <tr>
      <td><%= link_to grain_inventory.grain.name, grain_inventory unless grain_inventory.grain.nil? %></td>
      <td><%= grain_inventory.grain_supplier.name unless grain_inventory.grain_supplier.nil? %></td>
      <td><%= Units.format_mass_for_user(grain_inventory.amount,current_user) %></td>
      <td>
        <div class="pull-right">
          <%= link_to 'Destroy', grain_inventory, method: :delete, data: { confirm: 'Are you sure?', type: 'json'}, remote: 'true', :rel => 'nofollow', :class => 'btn btn-mini btn-danger delete_row' %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @grain_inventories %>

app/views/grain_inventories/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/grain_inventories/edit.html.erb
<h1>Editing Grain Inventory</h1>

<%= render 'form' %>

<%= link_to 'Show', @grain_inventory %> |
<%= link_to 'Back', grain_inventories_path %>

app/views/grain_inventories/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", grain_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_grain_inventory_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_grain_inventory_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      GrainInventory
    .inner
      = form_for @grain_inventory, :url => grain_inventory_path(@grain_inventory), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/grain_inventories/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'index_table' %>
<% end %>
<h1>Grain Inventory</h1>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <%= form_tag grain_inventories_path, :method => 'get', :id => "table_search", :class => "navbar-search pull-left", :autocomplete => "off" do %>
          <%= text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search" %>
        <% end %>
        <%= link_to raw('<i class="icon-plus-sign icon-white"></i> New Grain Transaction'), new_grain_transaction_path, :class => 'btn btn-primary pull-right'%>
      </div>
    </div>
  </div>
  <div id="index_table"><%= render 'grain_inventories' %></div>
</div>

app/views/grain_inventories/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", grain_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_grain_inventory_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      GrainInventories
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.grain_inventory.amount", :default => t("activerecord.labels.amount", :default => "Amount"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @grain_inventories.each do |grain_inventory|
          %tr{:class => cycle("odd", "even")}
            %td
              = grain_inventory.id
            %td
              = link_to grain_inventory.amount, grain_inventory_path(grain_inventory)
            %td
              = grain_inventory.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", grain_inventory_path(grain_inventory)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_grain_inventory_path(grain_inventory)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", grain_inventory_path(grain_inventory), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @grain_inventories
- content_for :sidebar, render(:partial => 'sidebar')

app/views/grain_inventories/index.js.erb
$("#index_table").html("<%= escape_javascript(render("grain_inventories")) %>");

app/views/grain_inventories/new.html.erb
<h1>New Grain Inventory</h1>

<%= render 'form' %>

<%= link_to 'Back', grain_inventories_path %>

app/views/grain_inventories/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", grain_inventories_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_grain_inventory_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      GrainInventory
    .inner
      = form_for :grain_inventory, :url => grain_inventories_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/grain_inventories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Grain Name:</b>
  <%= @grain_inventory.grain.name unless @grain_inventory.grain.nil? %>
</p>

<p>
  <b>Grain Supplier:</b>
  <%= @grain_inventory.grain_supplier.name unless @grain_inventory.grain_supplier.nil? %>
</p>

<p>
  <b>Amount:</b>
  <%= Units.format_mass_for_user(@grain_inventory.amount, current_user) %>
</p>

<p>
  <b>Grain Transactions:</b>
  <ul>
    <% @grain_inventory.grain_transactions.each do |t| %> 
      <li> <%= link_to "%s, Added on %s" % [Units.format_mass_for_user(t.amount * t.quantity, current_user), t.created_at.localtime.strftime('%F %r')], t %> </li>
    <% end %>
</ul> 
</p>

<%= link_to 'Edit', edit_grain_inventory_path(@grain_inventory) %> |
<%= link_to 'Back', grain_inventories_path %>

app/views/grain_inventories/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", grain_inventories_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_grain_inventory_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", grain_inventory_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.grain_inventory.amount", :default => t("activerecord.labels.amount", :default => "Amount"))
          \:
        = @grain_inventory.amount
      %p
        %b
          = t("activerecord.attributes.grain_inventory.grain_id", :default => t("activerecord.labels.grain_id", :default => "Grain"))
          \:
        = @grain_inventory.grain_id
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_grain_inventory_path(@grain_inventory), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), grain_inventory_path(@grain_inventory), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')