config/routes.rb
Brewtronic5000::Application.routes.draw do
  get "reporting/ttb"
  post "reporting/ttb"

  get "reporting/grain"
  post "reporting/grain"

  get "reporting/hop"
  post "reporting/hop"

  get "reporting/fermenter"
  post "reporting/fermenter"

  resources :hop_contracts

  resources :hop_transactions

  resources :grain_transactions

  resources :yeast_manufacturers

  resources :styles

  resources :recipe_minerals

  resources :recipes

  resources :mash_types

  resources :minerals

  resources :yeasts

  resources :batches

  resources :fermenters

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :hop_inventories

  get "home/index"

  resources :grain_inventories

  resources :grain_suppliers

  resources :grains

  resources :hop_suppliers

  resources :hops

  match 'recipes/:id/duplicate' => 'recipes#duplicate', :as => :duplicate_recipe
  match 'batches/:id/duplicate' => 'batches#duplicate', :as => :duplicate_batch

  authenticated :user do
      root :to => 'home#index'   
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    @batches = Batch.all
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_calendar.html.erb
<%= hidden_field_tag :month, params[:month] %>
<%= calendar @batches do |batch| %>
  <div>
    <ul>
      <li>
        <div class="well well-small">
          <%= link_to "%s (%s)" % [batch.recipe.name, batch.fermenter.name], batch %>
        </div>
      </li>
    </ul>
  </div>
<% end %>

app/views/home/_sidebar.html.haml
.block.notice
  %h3 Block 15
  .content
    %p Put something here 
.block
  %h3 Links
  %ul.navigation
    %li= link_to "Hop Inventory", hop_inventories_path
    %li= link_to "Grain Inventory", grain_inventories_path

app/views/home/index.html.erb
<h1> Newest Recipes</h1>
<ul>
  <% Recipe.all(:order => 'creation_date DESC', :limit => 7).each do |recipe| %>
    <li><%= link_to recipe.name, recipe%> </li>
  <% end %>
</ul>
<h1>Fermenter schedule</h1>
<div id="calendar">
  <%= render 'calendar' %>
</div>

app/views/home/index.html.haml
#block-text.block
  .content
    %h2.title Home
    %ul
      %li= link_to "Hops", hops_path
      %li= link_to "Hop Suppliers", hop_suppliers_path
      %li= link_to "Hop Inventory", hop_inventories_path
    %h2 Grain Management
    %ul
      %li= link_to "Grain", grains_path
      %li= link_to "Grain Inventory", grain_inventories_path
    %h2 Miscellaneous
    = link_to "Brewer", brewers_path
- content_for :sidebar, render(:partial => 'sidebar')

app/views/home/index.js.erb
$("#calendar").html("<%= escape_javascript(render("calendar")) %>");