config/routes.rb
Brewtronic5000::Application.routes.draw do
  get "reporting/ttb"
  post "reporting/ttb"

  get "reporting/grain"
  post "reporting/grain"

  get "reporting/hop"
  post "reporting/hop"

  get "reporting/fermenter"
  post "reporting/fermenter"

  resources :hop_contracts

  resources :hop_transactions

  resources :grain_transactions

  resources :yeast_manufacturers

  resources :styles

  resources :recipe_minerals

  resources :recipes

  resources :mash_types

  resources :minerals

  resources :yeasts

  resources :batches

  resources :fermenters

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :hop_inventories

  get "home/index"

  resources :grain_inventories

  resources :grain_suppliers

  resources :grains

  resources :hop_suppliers

  resources :hops

  match 'recipes/:id/duplicate' => 'recipes#duplicate', :as => :duplicate_recipe
  match 'batches/:id/duplicate' => 'batches#duplicate', :as => :duplicate_batch

  authenticated :user do
      root :to => 'home#index'   
  end

  root :to => 'home#index'

end

app/models/hop_supplier.rb
class HopSupplier < ActiveRecord::Base
  include Searchable
  attr_accessible :name, :hop_tokens
  attr_reader :hop_tokens
  has_many :hops
  has_many :hop_inventories, :dependent => :destroy
  has_many :hop_transactions, :dependent => :destroy
  has_many :hop_contracts, :dependent => :destroy
  validates_uniqueness_of :name

  self.per_page = 10

  def hop_tokens=(ids)
    self.hop_ids = ids.split(",")
  end

end

app/controllers/hop_suppliers_controller.rb
class HopSuppliersController < ApplicationController
  include SortableController
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  # GET /hop_suppliers
  # GET /hop_suppliers.json
  def index
    @hop_suppliers = HopSupplier.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page])
  end

  # GET /hop_suppliers/1
  # GET /hop_suppliers/1.json
  def show
    @hop_supplier = HopSupplier.find(params[:id])
  end

  # GET /hop_suppliers/new
  # GET /hop_suppliers/new.json
  def new
    @hop_supplier = HopSupplier.new
  end

  # GET /hop_suppliers/1/edit
  def edit
    @hop_supplier = HopSupplier.find(params[:id])
  end

  # POST /hop_suppliers
  # POST /hop_suppliers.json
  def create
    @hop_supplier = HopSupplier.new(params[:hop_supplier])

    respond_to do |format|
      if @hop_supplier.save
        format.html { redirect_to action: "index" and flash[:notice] = "Supplier #{@hop_supplier.name} was successfully created." }
        format.json { render json: @hop_supplier, status: :created, location: @hop_supplier }
      else
        format.html { render action: "new" }
        format.json { render json: @hop_supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hop_suppliers/1
  # PUT /hop_suppliers/1.json
  def update
    @hop_supplier = HopSupplier.find(params[:id])

    respond_to do |format|
      if @hop_supplier.update_attributes(params[:hop_supplier])
        format.html { redirect_to @hop_supplier, notice: 'Hop supplier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hop_supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hop_suppliers/1
  # DELETE /hop_suppliers/1.json
  def destroy
    @hop_supplier = HopSupplier.find(params[:id])
    @hop_supplier.destroy

    respond_to do |format|
      format.html { redirect_to hop_suppliers_url }
      format.json { head :no_content }
    end
  end

  def model
    HopSupplier
  end

end

app/helpers/hop_suppliers_helper.rb
module HopSuppliersHelper
end

app/views/hop_suppliers/_form.html.erb
<%= form_for(@hop_supplier) do |f| %>
  <% if @hop_supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hop_supplier.errors.count, "error") %> prohibited this hop_supplier from being saved:</h2>

      <ul>
      <% @hop_supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hop_suppliers/_form.html.haml
.group
  = f.label :name, t("activerecord.attributes.hop_supplier.name", :default => "Name"), :class => :label
  = f.text_field :name, :class => 'text_area'
  %span.description Ex: a simple text
.group.navform.wat-cf
  %button.button{:type => "submit"}
    = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
    = t("web-app-theme.save", :default => "Save")
  %span.text_button_padding= t("web-app-theme.or", :default => "or")
  = link_to t("web-app-theme.cancel", :default => "Cancel"), hop_suppliers_path, :class => "text_button_padding link_button"

app/views/hop_suppliers/_hop_suppliers.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @hop_suppliers.each do |hop_supplier| %>
    <tr>
      <td><%= link_to hop_supplier.name, hop_supplier%></td>
      <td>
        <div class="pull-right">
          <%= link_to 'Edit', edit_hop_supplier_path(hop_supplier), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', hop_supplier, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-mini btn-danger' %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @hop_suppliers %>

app/views/hop_suppliers/_sidebar.html.haml
.block.notice
  %h3 Simple Block
  .content
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/hop_suppliers/edit.html.erb
<h1>Editing Hop Supplier</h1>

<%= render 'form' %>

<%= link_to 'Show', @hop_supplier %> |
<%= link_to 'Back', hop_suppliers_path %>

app/views/hop_suppliers/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_suppliers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_supplier_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_hop_supplier_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      HopSupplier
    .inner
      = form_for @hop_supplier, :url => hop_supplier_path(@hop_supplier), :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_suppliers/index.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'index_table' %>
<% end %>
<h1>Hop Suppliers</h1>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <div class="nav-collapse">
        <%= form_tag hop_suppliers_path, :method => 'get', :id => "table_search", :class => "navbar-search pull-left", :autocomplete => "off" do %>
          <%= text_field_tag :search, params[:search], :class => "search-query", :placeholder => "Search" %>
        <% end %>
        <%= link_to raw('<i class="icon-plus-sign icon-white"></i> New Hop Supplier'), new_hop_supplier_path, :class => 'btn btn-primary pull-right'%>
      </div>
    </div>
  </div>
  <div id="index_table"><%= render 'hop_suppliers' %></div>
</div>

app/views/hop_suppliers/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "#{t("web-app-theme.list", :default => "List")}", hop_suppliers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_supplier_path
  .content
    %h2.title
      = t("web-app-theme.all", :default => "All")
      HopSuppliers
    .inner
      %table.table
        %tr
          %th.first ID
          %th
            = t("activerecord.attributes.hop_supplier.name", :default => t("activerecord.labels.name", :default => "Name"))
          %th= t("web-app-theme.created_at", :default => "Created at")
          %th.last &nbsp;
        - @hop_suppliers.each do |hop_supplier|
          %tr{:class => cycle("odd", "even")}
            %td
              = hop_supplier.id
            %td
              = link_to hop_supplier.name, hop_supplier_path(hop_supplier)
            %td
              = hop_supplier.created_at
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", hop_supplier_path(hop_supplier)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_hop_supplier_path(hop_supplier)} |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", hop_supplier_path(hop_supplier), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = paginate @hop_suppliers
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_suppliers/index.js.erb
$("#index_table").html("<%= escape_javascript(render("hop_suppliers")) %>");

app/views/hop_suppliers/new.html.erb
<h1>New Hop Supplier</h1>

<%= render 'form' %>

<%= link_to 'Back', hop_suppliers_path %>

app/views/hop_suppliers/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_suppliers_path
      %li.active= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_supplier_path
  .content
    %h2.title
      = t("web-app-theme.new", :default => "New")
      HopSupplier
    .inner
      = form_for :hop_supplier, :url => hop_suppliers_path, :html => { :class => :form } do |f|
        = render :partial => "form", :locals => {:f => f}
- content_for :sidebar, render(:partial => 'sidebar')

app/views/hop_suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @hop_supplier.name %>
</p>

<p>
  <b>Hops:</b>
  <ul>
    <% @hop_supplier.hops.each do |hop| %>
      <li><%= hop.name %></li>
    <% end %>
  </ul>
</p>
<%= link_to 'Edit', edit_hop_supplier_path(@hop_supplier) %> |
<%= link_to 'Back', hop_suppliers_path %>

app/views/hop_suppliers/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", hop_suppliers_path
      %li= link_to "#{t("web-app-theme.new", :default => "New")}", new_hop_supplier_path
      %li.active= link_to "#{t("web-app-theme.show", :default => "Show")}", hop_supplier_path
  .content
    .inner
      %p
        %b
          = t("activerecord.attributes.hop_supplier.name", :default => t("activerecord.labels.name", :default => "Name"))
          \:
        = @hop_supplier.name
      .wat-cf
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_hop_supplier_path(@hop_supplier), :class => "button"
        = link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), hop_supplier_path(@hop_supplier), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"
- content_for :sidebar, render(:partial => 'sidebar')